name: UHC
main: me.jjtcool.uhc.lobby.JoinEvent
version: 1.0.8
description: >
             A UHC plugin for the MCSquared Network
commands:
     setmynametag:
         description: Sets your nametag!
permissions:
    mcsq.changenametag:
        description: Can change nametag
    mcsq.donator.supporter:
        description: Supporter
    mcsq.donator.captain:
        description: Captain
    mcsq.donator.ultra:
        description: Ultra
    mcsq.donator.hero:
        description: Hero
    mcsq.staff.mod:
        description: Mod
    mcsq.staff.admin:
        description: Admin
    mcsq.staff.operator:
        description: Operator
    mcsq.staff.owner:
        description: Owner